#include "drivers/video/vga.h"

void kernel_main() {
  vga_clear_screen();
  vga_write_line("1");
  vga_write_line("2");
  vga_write_line("3");
  vga_write_line("4");
  vga_write_line("5");
  vga_write_line("6");
  vga_write_line("7");
  vga_write_line("8");
  vga_write_line("9");
  vga_write_line("10");
  vga_write_line("11");
  vga_write_line("12");
  vga_write_line("13");
  vga_write_line("14");
  vga_write_line("15");
  vga_write_line("16");
  vga_write_line("17");
  vga_write_line("18");
  vga_write_line("19");
  vga_write_line("20");
  vga_write_line("21");
  vga_write_line("22");
  vga_write_line("23");
  vga_write_line("24");
  vga_write_line("25");
  vga_write_line("26");
  vga_write_line("27");
  vga_write_line("28");
  vga_write_line("29");
  vga_write_line("30");
  vga_write_line("31");
  vga_write_line("32");
  vga_write_line("33");
  vga_write_line("34");
  vga_write_line("35");
  vga_write_line("36");
  vga_write_line("37");
  vga_write_line("38");
}